on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  TF_WORKSPACE: "terraform"
  TF_VARS_DEV_FILE: "tf-vars-dev.tfvars"
  TF_BACKEND_VARS_DEV_FILE: "backend-dev.tfvars"
  TF_PLAN_FILE: ".tfplanfile"

jobs:
  terraform-plan:
    name: "Terraform Plan and Comment on PR"
    # Permission can be added at job level or workflow level
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/terraform-plan.yml
    with: 
      env: "dev"
      terraform-version: "1.8.5"
      terraform-working-dir: "terraform"
      terraform-backend-config-file: "backend-dev.tfvars"
      terraform-vars-file: "tf-vars-dev.tfvars"
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-iam-role: ${{ secrets.FRUIT_PROJECT_DEV_AWS_ACCOUNT_ACCESS_ROLE }}
      git-token: ${{ secrets.FRUIT_PROJECT_GIT_TOKEN }}

  deploy-to-dev:
    name: Deploy to Dev in AWS
    permissions:
      id-token: write
      issues: write
      contents: read
    needs: terraform-plan
    uses: ./.github/workflows/terraform-plan-and-apply.yml
    with: 
      env: "dev"
      github-token: ${{ github.token }}
      terraform-version: "1.8.5"
      terraform-working-dir: "terraform"
      terraform-backend-config-file: "backend-dev.tfvars"
      terraform-vars-file: "tf-vars-dev.tfvars"
      terraform-plan-approvers: Kremzeeq
    secrets: 
      aws-region: ${{ secrets.AWS_REGION }}
      aws-iam-role: ${{ secrets.FRUIT_PROJECT_DEV_AWS_ACCOUNT_ACCESS_ROLE }}