on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-workflow.yml'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # Permission can be added at job level or workflow level
    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_FILE: "terraform.tfvars.json"
      # TF_WORKPLACE: "src/terraform"
      working-directory: ./"terraform"
    steps:
      # Use sparse checkout to only select files in mobile app directory
      # Turning off cone mode ensures that files in the project root are not included during checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'terraform'
          sparse-checkout-cone-mode: false

        # with: 
        #   path: "terraform/"
      # - name: Set AWS context
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
      #     role-session-name: GitHub_to_AWS_via_FederatedOIDC
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     mask-aws-account-id: true
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: '1.8.5'
      - name: Terraform Plan
        id: plan
        run: | 
          ls -la
          mv terraform/* .
          ls -la
        # working-directory: ${{env.working-directory}}
        # run: terraform plan -no-color -var-file ${{ env.TF_VAR_FILE }}
      #   continue-on-error: true
      # - uses: tchupp/actions-terraform-pr@v1
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     terraform apply -auto-approve -var-file ${{ env.TF_VAR_FILE }}
          


