on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-workflow.yml'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # Permission can be added at job level or workflow level
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      GH_WORKSPACE: "terraform"
      TF_VAR_FILE: "terraform.tfvars.json"

    steps:
      # Use sparse checkout to only select files in mobile app directory
      # Turning off cone mode ensures that files in the project root are not included during checkout
      # checkout pattern - https://github.com/actions/checkout/issues/483#issuecomment-1756354321
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.GH_WORKSPACE }}
          sparse-checkout-cone-mode: false
      - name: Move files to root
        id: plan
        run: |
            mv ${{ env.GH_WORKSPACE }}/* .
            rm -rf ${{ env.GH_WORKSPACE }}
            ls -lah
      - name: Set AWS context
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.8.5'
      - name: Setup Terraform Plan
        run: |
          terraform init
          terraform plan -no-color -var-file ${{ env.TF_VAR_FILE }} -out=plan.json
        continue-on-error: true
      - uses: tchupp/actions-terraform-pr@v1
        with:
          apply-branch: "main"
          # path: "terraform"
      # - name: PR comment Terraform plan
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     filePath: plan.json


      # - uses: tchupp/actions-terraform-pr@v1
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     terraform apply -auto-approve -var-file ${{ env.TF_VAR_FILE }}